# Ubuntu 14.04 Trusty support
sudo: required
dist: trusty

language:
  - cpp

compiler:
  - gcc

install:
  - sudo pip install cpp-coveralls
  - sudo apt-get install libsnappy-dev libleveldb1 libleveldb-dev
  #para jwtcpp
  - sudo apt-get install libcrypto++9 libcrypto++9-dbg libcrypto++-dev
  - sudo apt-get install libjansson4 libjansson-dev libjansson-dbg

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - ./test/run_tests

after_success:
  - coveralls --root .. -i src -E ".*CMakeFiles.*" -E ".*test/*/.*.cpp.*" --exclude src/jsoncpp --exclude lib --exclude test

#  -E ".*CMakeFiles.*" -E ".*test/.*.cpp.*"

notifications:
  slack: 7552-tallerii:TduWD2Mt2Vjsf9Or2hwCqYmK
  email: false

