# Ubuntu 14.04 Trusty support
sudo: required
dist: trusty

language:
  - cpp

compiler:
  - gcc

install:
  - sudo pip install cpp-coveralls

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - ./test/run_tests

after_success:
  - coveralls --root .. -E ".*CMakeFiles.*" -E ".*test/.*.cpp.*"

notifications:
  email: false