language:
  - cpp

install:
  - sudo pip install cpp-coveralls

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - ./test/run_tests

after_success:
  - coveralls --root .. -E ".*external.*" -E ".*CMakeFiles.*" -E ".*test/.*.cpp.*"

notifications:
  email: false