# Ubuntu 14.04 Trusty support
sudo: required
dist: trusty

language: cpp
python:
  - "2.7"

compiler:
  - gcc

install:
  - sudo pip install cpp-coveralls requests
  - sudo apt-get install python-requests
  - sudo apt-get install libsnappy-dev libleveldb-dev
  - sudo apt-get install libcrypto++9-dbg libcrypto++-dev
  - sudo apt-get install libjansson4 libjansson-dev libjansson-dbg
  - sudo apt-get install autoconf libtool
  - git clone https://github.com/mrtazz/restclient-cpp.git
  - cd restclient-cpp
  - ./autogen.sh
  - ./configure
  - sudo make install
  - export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH
  - cd ..

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - ./test/run_tests
  - /usr/bin/python ../test/api_tests/RestAPITest.py

after_success:
  - coveralls --root .. -i src -E ".*CMakeFiles.*" -E ".*test/*/.*.cpp.*" --exclude src/jsoncpp --exclude src/log/* --exclude test

notifications:
  slack: 7552-tallerii:TduWD2Mt2Vjsf9Or2hwCqYmK
  email: false

