.TH "ApiError" 3 "Wed Dec 7 2016" "Version 1.0.0" "Jobify" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ApiError \- 
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBsetError\fP (Mongoose::JsonResponse &response, int code, const char *message)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Jobify from the source code\&.
