.TH "cgi_env_block" 3 "Wed Dec 7 2016" "Version 1.0.0" "Jobify" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cgi_env_block \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBmg_connection\fP * \fBconn\fP"
.br
.ti -1c
.RI "char \fBbuf\fP [CGI_ENVIRONMENT_SIZE]"
.br
.ti -1c
.RI "const char * \fBvars\fP [MAX_CGI_ENVIR_VARS]"
.br
.ti -1c
.RI "int \fBlen\fP"
.br
.ti -1c
.RI "int \fBnvars\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Jobify from the source code\&.
