.TH "DatabaseManager" 3 "Wed Dec 7 2016" "Version 1.0.0" "Jobify" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DatabaseManager \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDatabaseManager\fP (std::string usersDbName, std::string sessionsDbName, std::string chatsDbName, std::string accountsDbName, std::string imagesDbName)"
.br
.ti -1c
.RI "bool \fBopenDBs\fP ()"
.br
.ti -1c
.RI "bool \fBadd_user\fP (const string &username, Json::Value user)"
.br
.ti -1c
.RI "Json::Value \fBget_user\fP (const string &username)"
.br
.ti -1c
.RI "bool \fBedit_user\fP (const string &username, Json::Value userEdited)"
.br
.ti -1c
.RI "bool \fBdelete_user\fP (const string &username)"
.br
.ti -1c
.RI "bool \fBget_users\fP (Json::Value &result)"
.br
.ti -1c
.RI "bool \fBrecommend_user\fP (const string &usernameFrom, const string &usernameTo)"
.br
.ti -1c
.RI "bool \fBdeRecommend_user\fP (const string &usernameFrom, const string &usernameTo)"
.br
.ti -1c
.RI "bool \fBaddContact\fP (const string &usernameFrom, const string &usernameTo)"
.br
.ti -1c
.RI "bool \fBremoveContact\fP (const string &usernameFrom, const string &usernameTo)"
.br
.ti -1c
.RI "bool \fBadd_session\fP (const std::string &token, Json::Value session)"
.br
.ti -1c
.RI "Json::Value \fBget_session\fP (const std::string &token)"
.br
.ti -1c
.RI "bool \fBdelete_session\fP (const std::string &token)"
.br
.ti -1c
.RI "bool \fBadd_account\fP (string username, string password)"
.br
.ti -1c
.RI "bool \fBis_correct\fP (std::string username, std::string password)"
.br
.ti -1c
.RI "bool \fBadd_msg\fP (string basic_string, std::string name_from, string basicString, string basic_string1)"
.br
.ti -1c
.RI "bool \fBget_conv\fP (string username, string username2, Json::Value *conversation)"
.br
.ti -1c
.RI "bool \fBget_convs\fP (string username, Json::Value *conversations)"
.br
.ti -1c
.RI "bool \fBdelete_conv\fP (string username, string username2)"
.br
.ti -1c
.RI "bool \fBdelete_msg\fP (string username1, string username2, string idMensaje)"
.br
.ti -1c
.RI "bool \fBget_users_by\fP (string sort_by, int nFilter, string job, string skill, Json::Value &result, int i, string basic_string)"
.br
.ti -1c
.RI "Json::Value \fBget_image\fP (string username)"
.br
.ti -1c
.RI "bool \fBadd_image\fP (const std::string &username, Json::Value &image)"
.br
.ti -1c
.RI "bool \fBdelete_image\fP (const std::string &username)"
.br
.ti -1c
.RI "void \fBfilter_pos\fP (Json::Value &result, int nDistance, string coordenates)"
.br
.ti -1c
.RI "void \fBsort_by_distance\fP (Json::Value &result, string coordenates)"
.br
.ti -1c
.RI "bool \fBget_user_contacts\fP (string &username, Json::Value &contacts)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Jobify from the source code\&.
