.TH "dir_entry" 3 "Wed Dec 7 2016" "Version 1.0.0" "Jobify" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dir_entry \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBconnection\fP * \fBconn\fP"
.br
.ti -1c
.RI "char * \fBfile_name\fP"
.br
.ti -1c
.RI "file_stat_t \fBst\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Jobify from the source code\&.
