.TH "el::base::debug" 3 "Wed Dec 7 2016" "Version 1.0.0" "Jobify" \" -*- nroff -*-
.ad l
.nh
.SH NAME
el::base::debug \- Contains some internal debugging tools like crash handler and stack tracer\&.  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCrashHandler\fP"
.br
.RI "\fIHandles unexpected crashes\&. \fP"
.ti -1c
.RI "class \fBStackTrace\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Contains some internal debugging tools like crash handler and stack tracer\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for Jobify from the source code\&.
