.TH "el::base::MillisecondsWidth" 3 "Wed Dec 7 2016" "Version 1.0.0" "Jobify" \" -*- nroff -*-
.ad l
.nh
.SH NAME
el::base::MillisecondsWidth \- A milliseconds width class containing actual width and offset for date/time\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <easylogging++\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMillisecondsWidth\fP (int width)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBMillisecondsWidth\fP &msWidth)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBm_width\fP"
.br
.ti -1c
.RI "unsigned int \fBm_offset\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A milliseconds width class containing actual width and offset for date/time\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Jobify from the source code\&.
