.TH "el::base::LogDispatcher" 3 "Wed Dec 7 2016" "Version 1.0.0" "Jobify" \" -*- nroff -*-
.ad l
.nh
.SH NAME
el::base::LogDispatcher \- Dispatches log messages\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <easylogging++\&.h>\fP
.PP
Inherits \fBel::base::NoCopy\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLogDispatcher\fP (bool proceed, \fBLogMessage\fP &&logMessage, \fBbase::DispatchAction\fP dispatchAction)"
.br
.ti -1c
.RI "void \fBdispatch\fP (void)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Dispatches log messages\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Jobify from the source code\&.
