.TH "el::base::PErrorWriter" 3 "Wed Dec 7 2016" "Version 1.0.0" "Jobify" \" -*- nroff -*-
.ad l
.nh
.SH NAME
el::base::PErrorWriter \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBel::base::Writer\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPErrorWriter\fP (\fBLevel\fP level, const char *file, unsigned long int line, const char *func, \fBbase::DispatchAction\fP dispatchAction=base::DispatchAction::NormalLog, base::type::VerboseLevel verboseLevel=0)"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for Jobify from the source code\&.
