.TH "el::base::HitCounter::Predicate" 3 "Wed Dec 7 2016" "Version 1.0.0" "Jobify" \" -*- nroff -*-
.ad l
.nh
.SH NAME
el::base::HitCounter::Predicate \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPredicate\fP (const char *filename, unsigned long int lineNumber)"
.br
.ti -1c
.RI "bool \fBoperator()\fP (const \fBHitCounter\fP *counter)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Jobify from the source code\&.
