.TH "el::base::utils::bitwise" 3 "Wed Dec 7 2016" "Version 1.0.0" "Jobify" \" -*- nroff -*-
.ad l
.nh
.SH NAME
el::base::utils::bitwise \- Bitwise operations for C++11 strong enum class\&. This casts e into Flag_T and returns value after bitwise operation Use these function as\&.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Bitwise operations for C++11 strong enum class\&. This casts e into Flag_T and returns value after bitwise operation Use these function as\&. 


.PP
.nf
flag = bitwise::Or<MyEnum>(MyEnum::val1, flag);
.fi
.PP
 
.SH "Author"
.PP 
Generated automatically by Doxygen for Jobify from the source code\&.
