.TH "el::base::type" 3 "Wed Dec 7 2016" "Version 1.0.0" "Jobify" \" -*- nroff -*-
.ad l
.nh
.SH NAME
el::base::type \- Data types used by Easylogging++\&.  

.SH SYNOPSIS
.br
.PP
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef char \fBchar_t\fP"
.br
.ti -1c
.RI "typedef std::string \fBstring_t\fP"
.br
.ti -1c
.RI "typedef std::stringstream \fBstringstream_t\fP"
.br
.ti -1c
.RI "typedef std::fstream \fBfstream_t\fP"
.br
.ti -1c
.RI "typedef std::ostream \fBostream_t\fP"
.br
.ti -1c
.RI "typedef unsigned short \fBEnumType\fP"
.br
.ti -1c
.RI "typedef std::shared_ptr< \fBbase::Storage\fP > \fBStoragePointer\fP"
.br
.ti -1c
.RI "typedef int \fBVerboseLevel\fP"
.br
.ti -1c
.RI "typedef std::shared_ptr< \fBLogDispatchCallback\fP > \fBLogDispatchCallbackPtr\fP"
.br
.ti -1c
.RI "typedef std::shared_ptr< \fBPerformanceTrackingCallback\fP > \fBPerformanceTrackingCallbackPtr\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Data types used by Easylogging++\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for Jobify from the source code\&.
