.TH "el::base::threading::internal::NoScopedLock< Mutex >" 3 "Wed Dec 7 2016" "Version 1.0.0" "Jobify" \" -*- nroff -*-
.ad l
.nh
.SH NAME
el::base::threading::internal::NoScopedLock< Mutex > \- Lock guard wrapper used when multi-threading is disabled\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <easylogging++\&.h>\fP
.PP
Inherits \fBel::base::NoCopy\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNoScopedLock\fP (\fBMutex\fP &)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename Mutex>
.br
class el::base::threading::internal::NoScopedLock< Mutex >"
Lock guard wrapper used when multi-threading is disabled\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Jobify from the source code\&.
