.TH "el::base::DefaultPerformanceTrackingCallback" 3 "Wed Dec 7 2016" "Version 1.0.0" "Jobify" \" -*- nroff -*-
.ad l
.nh
.SH NAME
el::base::DefaultPerformanceTrackingCallback \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBel::PerformanceTrackingCallback\fP\&.
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBhandle\fP (const \fBPerformanceTrackingData\fP *data)"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for Jobify from the source code\&.
