.TH "el::base::NullWriter" 3 "Wed Dec 7 2016" "Version 1.0.0" "Jobify" \" -*- nroff -*-
.ad l
.nh
.SH NAME
el::base::NullWriter \- Writes nothing - Used when certain log is disabled\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <easylogging++\&.h>\fP
.PP
Inherits \fBel::base::NoCopy\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNullWriter\fP & \fBoperator<<\fP (std::ostream &(*)(std::ostream &))"
.br
.ti -1c
.RI "template<typename T > \fBNullWriter\fP & \fBoperator<<\fP (const T &)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Writes nothing - Used when certain log is disabled\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Jobify from the source code\&.
