.TH "el::Configuration::Predicate" 3 "Wed Dec 7 2016" "Version 1.0.0" "Jobify" \" -*- nroff -*-
.ad l
.nh
.SH NAME
el::Configuration::Predicate \- Used to find configuration from configuration (pointers) repository\&. Avoid using it\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <easylogging++\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPredicate\fP (\fBLevel\fP \fBlevel\fP, \fBConfigurationType\fP \fBconfigurationType\fP)"
.br
.ti -1c
.RI "bool \fBoperator()\fP (const \fBConfiguration\fP *conf) const "
.br
.in -1c
.SH "Detailed Description"
.PP 
Used to find configuration from configuration (pointers) repository\&. Avoid using it\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Jobify from the source code\&.
