.TH "el::CustomFormatSpecifier" 3 "Wed Dec 7 2016" "Version 1.0.0" "Jobify" \" -*- nroff -*-
.ad l
.nh
.SH NAME
el::CustomFormatSpecifier \- User-provided custom format specifier\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <easylogging++\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCustomFormatSpecifier\fP (const char *formatSpecifier, const \fBFormatSpecifierValueResolver\fP &resolver)"
.br
.ti -1c
.RI "const char * \fBformatSpecifier\fP (void) const "
.br
.ti -1c
.RI "const \fBFormatSpecifierValueResolver\fP & \fBresolver\fP (void) const "
.br
.ti -1c
.RI "bool \fBoperator==\fP (const char *formatSpecifier)"
.br
.in -1c
.SH "Detailed Description"
.PP 
User-provided custom format specifier\&. 


.PP
\fBSee also:\fP
.RS 4
\fBel::Helpers::installCustomFormatSpecifier\fP 
.PP
\fBFormatSpecifierValueResolver\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Jobify from the source code\&.
