.TH "el::Callback< T >" 3 "Wed Dec 7 2016" "Version 1.0.0" "Jobify" \" -*- nroff -*-
.ad l
.nh
.SH NAME
el::Callback< T > \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBel::base::threading::ThreadSafe\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBenabled\fP (void) const "
.br
.ti -1c
.RI "void \fBsetEnabled\fP (bool enabled)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBhandle\fP (const T *handlePtr)=0"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Jobify from the source code\&.
