.TH "el::LogMessage" 3 "Wed Dec 7 2016" "Version 1.0.0" "Jobify" \" -*- nroff -*-
.ad l
.nh
.SH NAME
el::LogMessage \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLogMessage\fP (\fBLevel\fP level, const std::string &file, unsigned long int line, const std::string &func, base::type::VerboseLevel verboseLevel, \fBLogger\fP *logger)"
.br
.ti -1c
.RI "\fBLevel\fP \fBlevel\fP (void) const "
.br
.ti -1c
.RI "const std::string & \fBfile\fP (void) const "
.br
.ti -1c
.RI "unsigned long int \fBline\fP (void) const "
.br
.ti -1c
.RI "const std::string & \fBfunc\fP (void) const "
.br
.ti -1c
.RI "base::type::VerboseLevel \fBverboseLevel\fP (void) const "
.br
.ti -1c
.RI "\fBLogger\fP * \fBlogger\fP (void) const "
.br
.ti -1c
.RI "const base::type::string_t & \fBmessage\fP (void) const "
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Jobify from the source code\&.
