.TH "el::Loggers::ScopedRemoveFlag" 3 "Wed Dec 7 2016" "Version 1.0.0" "Jobify" \" -*- nroff -*-
.ad l
.nh
.SH NAME
el::Loggers::ScopedRemoveFlag \- Removes flag and add it when scope goes out\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <easylogging++\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBScopedRemoveFlag\fP (\fBLoggingFlag\fP flag)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Removes flag and add it when scope goes out\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Jobify from the source code\&.
