.TH "el::LogDispatchData" 3 "Wed Dec 7 2016" "Version 1.0.0" "Jobify" \" -*- nroff -*-
.ad l
.nh
.SH NAME
el::LogDispatchData \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "const \fBLogMessage\fP * \fBlogMessage\fP (void) const "
.br
.ti -1c
.RI "\fBbase::DispatchAction\fP \fBdispatchAction\fP (void) const "
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBbase::LogDispatcher\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Jobify from the source code\&.
