.TH "el::VersionInfo" 3 "Wed Dec 7 2016" "Version 1.0.0" "Jobify" \" -*- nroff -*-
.ad l
.nh
.SH NAME
el::VersionInfo \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBel::base::StaticClass\fP\&.
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static const std::string \fBversion\fP (void)"
.br
.RI "\fICurrent version number\&. \fP"
.ti -1c
.RI "static const std::string \fBreleaseDate\fP (void)"
.br
.RI "\fIRelease date of current version\&. \fP"
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Jobify from the source code\&.
