.TH "Json::CommentStyle" 3 "Wed Dec 7 2016" "Version 1.0.0" "Jobify" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Json::CommentStyle \- Scoped enums are not available until C++11\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBEnum\fP { \fBNone\fP, \fBMost\fP, \fBAll\fP }
.RI "\fIDecide whether to write comments\&. \fP""
.br
.in -1c
.SH "Detailed Description"
.PP 
Scoped enums are not available until C++11\&. 
.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBJson::CommentStyle::Enum\fP"

.PP
Decide whether to write comments\&. 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fINone \fP\fP
Drop all comments\&. 
.TP
\fB\fIMost \fP\fP
Recover odd behavior of previous versions (not implemented yet)\&. 
.TP
\fB\fIAll \fP\fP
Keep all comments\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Jobify from the source code\&.
