.TH "Json::OurCharReader" 3 "Wed Dec 7 2016" "Version 1.0.0" "Jobify" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Json::OurCharReader \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBJson::CharReader\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBOurCharReader\fP (bool collectComments, \fBOurFeatures\fP const &features)"
.br
.ti -1c
.RI "bool \fBparse\fP (char const *beginDoc, char const *endDoc, \fBValue\fP *root, JSONCPP_STRING *errs) JSONCPP_OVERRIDE"
.br
.RI "\fIRead a \fBValue\fP from a \fCJSON\fP document\&. The document must be a UTF-8 encoded string containing the document to read\&. \fP"
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "bool Json::OurCharReader::parse (char const * beginDoc, char const * endDoc, \fBValue\fP * root, JSONCPP_STRING * errs)\fC [inline]\fP, \fC [virtual]\fP"

.PP
Read a \fBValue\fP from a \fCJSON\fP document\&. The document must be a UTF-8 encoded string containing the document to read\&. 
.PP
\fBParameters:\fP
.RS 4
\fIbeginDoc\fP Pointer on the beginning of the UTF-8 encoded string of the document to read\&. 
.br
\fIendDoc\fP Pointer on the end of the UTF-8 encoded string of the document to read\&. Must be >= beginDoc\&. 
.br
\fIroot\fP [out] Contains the root value of the document if it was successfully parsed\&. 
.br
\fIerrs\fP [out] Formatted error messages (if not NULL) a user friendly string that lists errors in the parsed document\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
\fCtrue\fP if the document was successfully parsed, \fCfalse\fP if an error occurred\&. 
.RE
.PP

.PP
Implements \fBJson::CharReader\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Jobify from the source code\&.
