.TH "Json::Writer" 3 "Wed Dec 7 2016" "Version 1.0.0" "Jobify" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Json::Writer \- Abstract class for writers\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <json\&.h>\fP
.PP
Inherited by \fBJson::FastWriter\fP, and \fBJson::StyledWriter\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual JSONCPP_STRING \fBwrite\fP (const \fBValue\fP &root)=0"
.br
.in -1c
.SH "Detailed Description"
.PP 
Abstract class for writers\&. 


.PP
\fBDeprecated\fP
.RS 4
Use \fBStreamWriter\fP\&. (And really, this is an implementation detail\&.) 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Jobify from the source code\&.
