.TH "Json::RuntimeError" 3 "Wed Dec 7 2016" "Version 1.0.0" "Jobify" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Json::RuntimeError \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <json\&.h>\fP
.PP
Inherits \fBJson::Exception\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRuntimeError\fP (JSONCPP_STRING const &msg)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Exceptions which the user cannot easily avoid\&.
.PP
E\&.g\&. out-of-memory (when we use malloc), stack-overflow, malicious input
.PP
\fBRemarks:\fP
.RS 4
derived from \fBJson::Exception\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Jobify from the source code\&.
