.TH "Json::OurReader::StructuredError" 3 "Wed Dec 7 2016" "Version 1.0.0" "Jobify" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Json::OurReader::StructuredError \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "ptrdiff_t \fBoffset_start\fP"
.br
.ti -1c
.RI "ptrdiff_t \fBoffset_limit\fP"
.br
.ti -1c
.RI "JSONCPP_STRING \fBmessage\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Jobify from the source code\&.
