.TH "Mongoose::RequestHandlerBase" 3 "Wed Dec 7 2016" "Version 1.0.0" "Jobify" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Mongoose::RequestHandlerBase \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBMongoose::RequestHandler< T, R >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fBResponse\fP * \fBprocess\fP (\fBRequest\fP &request)=0"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Jobify from the source code\&.
