.TH "Mongoose::JsonResponse" 3 "Wed Dec 7 2016" "Version 1.0.0" "Jobify" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Mongoose::JsonResponse \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ProfileController\&.h>\fP
.SH "Detailed Description"
.PP 
to store the response json\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Jobify from the source code\&.
