.TH "Mongoose::StreamResponse" 3 "Wed Dec 7 2016" "Version 1.0.0" "Jobify" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Mongoose::StreamResponse \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits ostringstream, and \fBMongoose::Response\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual string \fBgetBody\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Member Function Documentation"
.PP 
.SS "string Mongoose::StreamResponse::getBody ()\fC [virtual]\fP"
Gets the response body
.PP
\fBReturns:\fP
.RS 4
string the response body 
.RE
.PP

.PP
Implements \fBMongoose::Response\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Jobify from the source code\&.
