.TH "Moongose::Request" 3 "Wed Dec 7 2016" "Version 1.0.0" "Jobify" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Moongose::Request \- 
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Controller that manages the user related api endpoints\&. Every method recieves a request data and a 

.SH "Author"
.PP 
Generated automatically by Doxygen for Jobify from the source code\&.
