.TH "RestAPITest.TestCase" 3 "Wed Dec 7 2016" "Version 1.0.0" "Jobify" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RestAPITest.TestCase \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits TestCase\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fBsetUp\fP (self)"
.br
.ti -1c
.RI "def \fBCategoryRequestInsert\fP (self, name, description)"
.br
.ti -1c
.RI "def \fBCategoryInsertSimple\fP (self, name, description)"
.br
.ti -1c
.RI "def \fBCategoryInsertSimpleExpectedError\fP (self, name, description)"
.br
.ti -1c
.RI "def \fBCategoryDeleteSimple\fP (self, name)"
.br
.ti -1c
.RI "def \fBgetCategories\fP (self)"
.br
.ti -1c
.RI "def \fBcheckEmptyBD\fP (self)"
.br
.ti -1c
.RI "def \fBupdateCategory\fP (self, oldName, newName, newDescription)"
.br
.ti -1c
.RI "def \fBtestCategoryInsertAndDelete\fP (self)"
.br
.ti -1c
.RI "def \fBtestCategoryIntertTwoDeleteTwo\fP (self)"
.br
.ti -1c
.RI "def \fBtestInsertTwiceGetError\fP (self)"
.br
.ti -1c
.RI "def \fBtestUpdateCategory\fP (self)"
.br
.ti -1c
.RI "def \fBtestInsertDeleteUpdateMixed\fP (self)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Jobify from the source code\&.
